Adding responsive design
DRAGONcodex45/p2pplaftorm pull request #3
Opened 2024-11-23 02:06 UTC by DRAGONcodex45

Changes:

-Media quaries for mobile fixed
-Responsive design for tablet fixed
-Card layout fixed for proper display
-CSS errors fixed

2024-11-23 23:00 UTC, JBXCOIN requested changes

2024-11-23 23:00 UTC, JBXCOIN commented on src/styles.css
> +}
.You might want to check the breakpoint of tablet screen

2024-11-23 23:00 UTC, JBXCOIN commented on src/index.html
>              <div class="navbar">
.Navbar hamburger menu not responsive, please fix

2024-11-24 17:27 UTC, DRAGONcodex45 commented on src/styles.css
> +}
Fixed

2024-11-24 17:36 UTC, merged